#ifndef COMMON_H
#define COMMON_H

#define CLONE_NEWNS      0x00020000
#define CLONE_NEWCGROUP  0x02000000
#define CLONE_NEWUTS     0x04000000
#define CLONE_NEWIPC     0x08000000
#define CLONE_NEWUSER    0x10000000
#define CLONE_NEWPID     0x20000000
#define CLONE_NEWNET     0x40000000
#define CLONE_NEWTIME    0x00000080
#define NS_MASK (CLONE_NEWNS|CLONE_NEWCGROUP|CLONE_NEWUTS|CLONE_NEWIPC|CLONE_NEWUSER|CLONE_NEWPID|CLONE_NEWNET|CLONE_NEWTIME)


#define MAX_CONTAINERS 1024
#define MAX_PREFIX_LEN 24


enum events_type {
    EVT_CLONE = 0,
    EVT_UNSHARE,
    EVT_SETNS,
    EVT_CGROUP_MKDIR,
    EVT_CGROUP_RMDIR,
    EVT_FORK,
    EVT_EXEC,
    EVT_EXIT,
    EVT_CLONE_EXIT,
    EVT_UNSHARE_EXIT,
    EVT_SETNS_EXIT,
    EVT_OPEN,
    EVT_OPENAT,
    EVT_OPEN_EXIT,
    EVT_OPENAT_EXIT,
    EVT_WRITE,
    EVT_CLOSE,
    EVT_WRITE_EXIT
};

#endif