apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: containerspy
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    matchLabels:
      app: containerspy
  template:
    metadata:
      labels:
        app: containerspy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      hostNetwork: true
      imagePullSecrets:
      - name: regcred
      securityContext:
        seLinuxOptions:
          level: "s0:c123,c456"
      initContainers:
      - name: init-log-dir
        image: busybox
        command: ["sh", "-c", "mkdir -p /var/log/containerSpy && chown -R 1000:1000 /var/log/containerSpy"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: log-volume
          mountPath: /var/log/containerSpy
      containers:
      - name: containerspy
        image: chris3bass/containerspy:latest
        ports:
        - containerPort: 8080
          name: metrics
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_RESOURCE
        volumeMounts:
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: proc
          mountPath: /proc
          readOnly: false
        - name: log-volume
          mountPath: /var/log/containerSpy
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
      - name: log-volume
        hostPath:
          path: /var/log/containerSpy
          type: DirectoryOrCreate

