apiVersion: v1
kind: Pod
metadata:
  name: multi-container-test
  labels:
    app: containerspy-test
spec:
  nodeSelector:
    kubernetes.io/hostname: nodo3
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep 1d"]  # Mantiene el container vivo para pruebas
    securityContext:
      privileged: true                     # Necesario para usar unshare, setns, etc.
    stdin: true
    tty: true
