apiVersion: v1
kind: Pod
metadata:
  name: pod-nodo2
  labels:
    app: containerspy
spec:
  nodeSelector:
    kubernetes.io/hostname: nodo2
  containers:
  - name: alpine-1
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      privileged: true
    stdin: true
    tty: true
  - name: alpine-2
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      privileged: true
    stdin: true
    tty: true

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nodo3
  labels:
    app: containerspy
spec:
  nodeSelector:
    kubernetes.io/hostname: nodo3
  containers:
  - name: alpine-1
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      privileged: true
    stdin: true
    tty: true
  - name: alpine-2
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      privileged: true
    stdin: true
    tty: true
